### ISSUE TITLE
command: arc linters no longer display whether its configured or not

### ISSUE THREAD

**Issue by alcedo** [phacility/arcanist#175]
$ arc linters should display: http://cl.ly/image/3Q120x3H1M3E 

the latest build doesnt show the [configured] status

the last working hash that works is -> e37a768

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
