### ISSUE TITLE
Severity often does not work in .arclint

### ISSUE THREAD

**Issue by philolo1** [phacility/arcanist#188]
In the doc https://secure.phabricator.com/book/phabricator/article/arcanist_lint/ it sounds like that severity is implemented for all the linters. Also if you type arc linters --verbose it is telling you that there parameters exists. But for many linters like (gjslint/xhppast) one cannot do this, since it is not implemented. So please change the description, because it was taking me hours to figure out that the functionality is missing, I thought I was doing something wrong...

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
