### ISSUE TITLE
ArcanistScriptAndRegexLinter not usable?

### ISSUE THREAD

**Issue by philolo1** [phacility/arcanist#189]
I tried to use ArcanistScriptAndRegexLinter.php in .arclint, but i got 

Got unexpected parameters: linter.scriptandregex.script

my file looked like this:

{                                                                                   
  "linters": {                                                                      
    "sample": {                                                                     
      "type": "jshint",                                                             
        "include": "(\\.js$)",                                                      
        "severity": {                                                               
          "W030" : "disabled"                                                       
        }                                                                           
    },                                                                              
      "space-linter": {                                                             
        "type": "script-and-regex",                                                 
        "linter.scriptandregex.script": "sh -c 'test.sh'"                           
      }                                                                             
                                                                                    
  }                                                                                 
}

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
