### ISSUE TITLE
"arc commit --show" doesn't do what it says on the tin

### ISSUE THREAD

**Issue by jayfoad** [phacility/arcanist#190]
The help for "arc commit --show" says "Show the command which would be issued, but do not actually commit anything." In practice it does not show the command which would be issued; it just shows the log message that will be used for the commit.

I'd find it very helpful if it did show me the command, or at least gave me some feedback about exactly which files will be committed (e.g. with a diffstat or something).

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
