### ISSUE TITLE
Unable to change severity of lint errors raised by Text linter

### ISSUE THREAD

**Issue by jaseemabid** [phacility/arcanist#192]
Bad charset causes error `TXT5` (LINT_BAD_CHARSET) and adding the following to `.arclint` is not suppressing the warnings. 

    "linters" : {
        "text": {
            "type": "text",
            "text.max-line-length": 300,
            "severity" : {
                "TXT5" : "disabled"
            }
        },

**Comment by chadlittle** [comment]
We no longer accepts bug reports and feature requests on GitHub. Please take the time to:

- Update your install to HEAD.
- Verify issue still persists.
- File task on https://secure.phabricator.com/ with steps to overly complete steps to reproduce.

More information on filing bug reports:
https://secure.phabricator.com/book/phabcontrib/article/bug_reports/

More information on filing feature requests:
https://secure.phabricator.com/book/phabcontrib/article/feature_requests/

Thank you for your interest in Phabricator.
