### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by gorangasic** [phacility/arcanist#197]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with arcanist. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable arcanist on @Sourcegraph by going to https://sourcegraph.com/github.com/phacility/arcanist and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by chadlittle** [comment]
We're not likely to pursue this in the upstream.
