### ISSUE TITLE
Arc land/diff with rebased branches

### ISSUE THREAD

**Issue by jcarrillo7** [phacility/arcanist#198]
Is there a proper way to use arc land with rebased branches?

My issue is that I made a branch A made changes and submitted for review, meanwhile a commit landed on master that I wanted to use in my branch A to test with so I rebased branch A with master. When doing arc diff later to update branch A review it either updates a closed commit, fails, or create a brand new diff. Once it even let me approve my own review somehow.

Here is a screen shot of approving a review by the person who owns it. Austin in this pic approved his own review.
![screen shot 2015-01-23 at 2 02 14 am](https://cloud.githubusercontent.com/assets/1562339/5872973/3d96bb0a-a2a6-11e4-91d1-c8a2a42178b0.png)

Any ideas?

**Comment by chadlittle** [comment]
Not clear what your core question is but here is the manual:
https://secure.phabricator.com/book/phabricator/article/differential_faq/

Basically, we trust developers by default. If person A accepts, and you make changes, rebase, whatever, that accept still is an accept. Go ahead and land when you've finished moving that submit button 4 pixels.

Or, turn sticky accept off if you find it confusing or incorrect, theres a setting.

**Comment by jcarrillo7** [comment]
The accept issue was just something random. My main question is about if arc diff will behave properly and update the right review when the branched has been rebased after a review has been made on it?

**Comment by chadlittle** [comment]
I'm not aware of any issues with that workflow, it's the one I use.
